### ISSUE TITLE
关于联邦推荐系统设计

### ISSUE THREAD

**Issue by TaoHaoTian** [XYT2000/Fedral-Recommendation-Movie#2]
作者你好，作为一名科研小白最近在学习联邦学习，步履维艰，想向您请教学习。能否加一下您的联系方式，附上我的邮箱：taohao_edu@163.com

**Comment by XYT2000** [comment]
抱歉兄弟我现在也只是一个刚刚起步学这个的大四学生，步履可能比你更加艰难，我已经被它整自闭了。而且最近我在准备研究生复试，可能暂时也没有太多时间去研究联邦学习.
PS：如果你也是使用FATE框架的话可以微信关注“FATE开源社区”，里面可以加相关的群。

**Comment by xyt2000** [comment]
> 作者你好，作为一名科研小白最近在学习联邦学习，步履维艰，想向您请教学习。能否加一下您的联系方式，附上我的邮箱：[taohao_edu@163.com](mailto:taohao_edu@163.com)

抱歉兄弟我现在也只是一个刚刚起步学这个的大四学生，步履可能比你更加艰难，我已经被它整自闭了。而且最近我在准备研究生复试，可能暂时也没有太多时间去研究联邦学习.
PS：如果你也是使用FATE框架的话可以微信关注“FATE开源社区”，里面可以加相关的群。

**Comment by TaoHaoTian** [comment]
兄弟，复试加油




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XYT2000/Fedral-Recommendation-Movie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XYT2000/Fedral-Recommendation-Movie] 关于联邦推荐系统设计 (#2)





  
***@***.***
  
抱歉兄弟我现在也只是一个刚刚起步学这个的大四学生，步履可能比你更加艰难，我已经被它整自闭了。而且最近我在准备研究生复试，可能暂时也没有太多时间去研究联邦学习.
 PS：如果你也是使用FATE框架的话可以微信关注“FATE开源社区”，里面可以加相关的群。

**Comment by wxs521666** [comment]
大佬能不能讲一下您这个项目的环境啊

**Comment by xyt2000** [comment]
> 大佬能不能讲一下您这个项目的环境啊

已更新readme 只能说要是用FATE的话只能用老版本，效果也不好

**Comment by huhu-afk** [comment]
大佬 有更新后的代码吗

**Comment by xyt2000** [comment]
> 大佬 有更新后的代码吗

代码毕业后就不在了，你要是要搭系统上线的话肯定要用到fate-serving，我找到一个教程你可以参考一下：https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/FATE-SERVING-2.0.html

**Comment by DY49301** [comment]
大佬，您这个联邦推荐的过程能再详细点吗，我不太理解这个推荐的过程。

**Comment by DY49301** [comment]
用户不是要在客户端本地利用自己的数据训练模型吗

**Comment by xyt2000** [comment]
> 大佬，您这个联邦推荐的过程能再详细点吗，我不太理解这个推荐的过程。

可以参考https://github.com/FederatedAI/FATE/tree/v1.3.1/federatedrec，

具体过程你可以按照标题搜索相应的论文

**Comment by DY49301** [comment]
谢谢大佬，还有个问题就是我用了你的地址也还是下不了1.3.1版本的

**Comment by xyt2000** [comment]
不会吧 我刚才看还在呢，你看看是不是中间有个空格没删除

**Comment by DY49301** [comment]
> 不会吧 我刚才看还在呢，你看看是不是中间有个空格没删除

噢噢，我没看见空格，谢谢佬

**Comment by DY49301** [comment]
> 

大佬，如果可以的话，方便加下联系方式咨询一下吗，我的QQ: 2534501547 微信: DY39401 , 有偿，感谢大佬

**Comment by xyt2000** [comment]
> > 
> 
> 大佬，如果可以的话，方便加下联系方式咨询一下吗，我的QQ: 2534501547 微信: DY39401 , 有偿，感谢大佬

不好意思我现在可能也帮不了你什么，我这两年也没有接触联邦学习方向的东西
